{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "csye7125-consumer.fullname" . }}-network-policy
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "csye7125-consumer.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "csye7125-consumer.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
{{- end }}